### ISSUE TITLE
"Michael R Gustafson II" (EGR 103) breaks our code.

### ISSUE THREAD

**Issue by shamystic** [williamyeny/duke-ratemyprofessors#5]
Is there even a solution to this? They're still alphabetic characters too

**Comment by williamyeny** [comment]
yeah, file a complaint against him so Duke fires him and removes him from course page.

duh.

**Comment by williamyeny** [comment]
"Jr" breaks it as well. Check out "intro to jazz" in AAAS

**Comment by shamystic** [comment]
Fixed
